(load "test.scm")
(define nil '())
(define (entry tree) (car tree))
(define (entry-of-list l) (car l))
(define (left-branch tree) (cadr tree))
(define (right-branch tree) (caddr tree))
(define (make-tree entry left right)
  (list entry left right)
  )

(define (element-of-set? x set)
  (cond ((null? set) #f)
        ((= x (entry set)) #t)
        ((< x (entry set)) (element-of-set? x (left-branch set)))
        ((> x (entry set)) (element-of-set? x (right-branch set)))
        )
  )

(define (adjoin-set x set)
  (cond ((null? set) (make-tree x nil nil))
        ((= x (entry set)) set)
        ((< x (entry set)) 
         (make-tree (entry set) 
                    (adjoin-set x (left-branch set)) 
                    (right-branch set))
         )
        ((> x (entry set)) 
         (make-tree (entry set) 
                    (left-branch set)
                    (adjoin-set x (right-branch set)))
         )
        )
  )

(define (union-set set1 set2)
  (define (union-list list1 list2)
    (cond ((and (null? list1) (null? list2)) '())
          ((null? list1) list2)
          ((null? list2) list1)
          (else
           (let ((x1 (entry-of-list list1))
                 (x2 (entry-of-list list2)))
             (cond ((= x1 x2)
                    (cons x1 (cons x2 (union-list (cdr list1) (cdr list2))))
                    )
                   ((< x1 x2)
                    (cons x1 (union-list (cdr list1) list2))
                    )
                   ((> x1 x2)
                    (cons x2 (union-list list1 (cdr list2)))
                    )                 
                   )
             )
           )
          )    
    )
  
  (let ((list1 (tree->list set1))
        (list2 (tree->list set2)))
    (list->tree (union-list list1 list2))    
    )
  )

(define (intersection-set set1 set2)
  (define (intersection-list list1 list2)
    (if (or (null? list1) (null? list2)) 
        '()
        (let ((x1 (entry-of-list list1))
              (x2 (entry-of-list list2)))
          (cond ((= x1 x2)
                 (cons x1 (intersection-list (cdr list1) (cdr list2)))
                 )
                ((< x1 x2)
                 (intersection-list (cdr list1) list2)
                 )
                ((> x1 x2)
                 (intersection-list list1 (cdr list2))
                 )
                )
          )
        )
    
    )
      
  (let ((list1 (tree->list set1))
        (list2 (tree->list set2)))
    (list->tree (intersection-list list1 list2))    
    )
  )

(define (tree->list-1 tree)
  (if (null? tree) 
      '()
      (append (tree->list-1 (left-branch tree)) 
              (cons (entry tree) 
                    (tree->list-1 (right-branch tree))))
      )
  )

(define (tree->list-2 tree)
  (define (copy-to-list tree result-list)
    (if (null? tree)
        result-list
        (copy-to-list (left-branch tree)
                      (cons (entry tree) 
                            (copy-to-list (right-branch tree) result-list)))
        )
    )
  (copy-to-list tree '())
  )

(define (list->tree e)
  (car (partial-tree e (length e)))
  )
(define (partial-tree e n)
  (if (= n 0)
      (cons '() e)
      (let ((left-size (quotient (- n 1) 2)))
        (let ((left-result (partial-tree e left-size)))
          (let ((left-tree (car left-result))
                (non-left-elts (cdr left-result))
                (right-size (- n (+ left-size 1))))
            (let ((this-entry (car non-left-elts))
                  (right-result (partial-tree (cdr non-left-elts) right-size)))
              (let ((right-tree (car right-result))
                    (remaining-elts (cdr right-result)))
                (cons (make-tree this-entry left-tree right-tree) remaining-elts)       
                )
              )
            )
          )
        ) 
      )
  )

(define (tree->list tree)
  (define (copy-to-list tree result-list)
    (if (null? tree)
        result-list
        (copy-to-list (left-branch tree)
                      (cons (entry tree) 
                            (copy-to-list (right-branch tree) result-list)))
        )
    )
  (copy-to-list tree '())
  )

(define a (make-tree 1 nil nil))
(define b (make-tree 5 nil nil))
(define c (make-tree 11 nil nil))
(define d (make-tree 3 a b))
(define e (make-tree 9 nil c))
(define x (make-tree 7 d e))

(define a (make-tree 1 nil nil))
(define b (make-tree 5 nil nil))
(define c (make-tree 11 nil nil))
(define d (make-tree 9 nil c))
(define e (make-tree 7 b d))
(define y (make-tree 3 a e))

(define a (make-tree 1 nil nil))
(define b (make-tree 7 nil nil))
(define c (make-tree 11 nil nil))
(define d (make-tree 3 a nil))
(define e (make-tree 9 b c))
(define z (make-tree 5 d e))

(define t '(1 3 5 7 9 11))
(define t2 '(2 4 6 8 10 12))
(define t3 '(1 2 3 4 5 6 7 8 9 10 11 12))


(define (test)
  (testing (list (tree->list-1 x)
                 (tree->list-2 x)
                 (tree->list-1 y)
                 (tree->list-2 y)
                 (tree->list-1 z)
                 (tree->list-2 z)
                 x
                 y
                 z
                 (list->tree t)
                 (union-set (list->tree t) (list->tree t2))
                 (tree->list (union-set (list->tree t) (list->tree t2)))
                 (intersection-set (list->tree t) (list->tree t2))
                 (tree->list (intersection-set (list->tree t) (list->tree t2)))
                 (intersection-set (list->tree t3) (list->tree t2))
                 (tree->list (intersection-set (list->tree t3) (list->tree t2)))
                 (intersection-set (list->tree t) (list->tree t3))
                 (tree->list (intersection-set (list->tree t) (list->tree t3)))
                  
            )
           )
  )












