(define (testing cases)
  (cond ((null? cases)
         (newline)
         "succesfully end"
         )
        (else
         (newline)
         (display (car cases))
         (newline)
         (testing (cdr cases)) 
         )     
      )
  )


(define (tree-testing cases)
  (define (iter l)
    (cond ((null? (cdr l))
           (newline)
           (display (car l))
           (newline)
           )
          (else
           (newline)
           (display (car l))
           (iter (cdr l))           
           )
        )
    )
  )
