(define (testing cases)
  (define (iter l)
    (cond ((null? (cdr l))
           (newline)
           (display (car l))
           (newline)
           )
          (else
           (newline)
           (display (car l))
           (iter (cdr l))           
           )
        )
    )
  
  (cond ((null? cases)
         (newline)
         "succesfully end"
         )        
        ((list? (car cases))
         (iter (car cases))
         (testing (cdr cases))
         )
        (else
         (newline)
         (display (car cases))
         (newline)
         (testing (cdr cases)) 
         )     
      )
  )