(load "test")

(define (make-account balance)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        "Insufficient funds"
        ))
  (define (deposit amount)
    (set! balance (+ balance amount))
    )
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          ((eq? m 'balance) balance)
          (else (error "Uknown request - MAKE-ACCOUNT" m))          
          )
    )
  dispatch)

(define (test)
  (define acc1 (make-account 100))
  (define acc2 (make-account 100))
  (append-item (acc1 'balance))
  (append-item (acc2 'balance))
  (append-item ((acc1 'withdraw) 50))
  (append-item ((acc2 'withdraw) 30))
  (append-item (acc1 'balance))
  (append-item (acc2 'balance))
  
  (testing results-list)
  )