(load "average-damp.scm")
(load "fixed-point.scm")
(load "repeated.scm")
(load "pow.scm")

(define (get-max-pow n)
  (define (iter p r)
    (if (< (- n r) 0)
        (- p 1)
        (iter (+ p 1) (* r 2))
        )              
    )
  (iter 1 2)
  )

(define (nth-root n x)
  (fixed-point ((repeated average-damp (get-max-pow n))
                (lambda (y) (/ x (pow y (- n 1)))))
                1.0)
  )